---
- name: install iptables package
  yum: 
    name="iptables"
    state="present"
  sudo: yes
  sudo_user: root
  notify:
    - start iptables

- name: Allow traffic
  command: "iptables -I INPUT 1 -i {{ item.interface }}  -p tcp --dport {{ item.port }}  -m state --state NEW,ESTABLISHED -j ACCEPT"
  with_items: allow-ports
  notify:
    - save iptables
